### ISSUE TITLE
Coordinating r-base updates

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-base-feedstock#46]
There are lots of changes to be made to the r-base recipe. We need to decide which changes we make simultaneously and which we do in independent stages:

- [x] ~~Migrate to conda-build 3~~ #47
- [x] ~~Update to R 3.5.1 (to be released on July 2)~~ #56, https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/107
- [x] Re-arrange Windows R layout to be the same as Unix ~~#43~~ ~~#57~~ #61
- [x] Support MRO compatibility #34 #61 
- [x] Drop support for win-32 #60 #61
- [x] Install `{{native}}icu` on Windows conda-forge/staged-recipes#6690 #61

For me, the highest priority are the first two items. I propose we migrate to conda-build 3 and update to R 3.5.1 together as the next big change.

Re-arranging the Windows R layout to be the same as Unix is still a work-in-progress, and would involve updating the R package recipes to properly find the license files shipped with r-base. Thus I think this change should wait until after the big update to 3.5.1.

If we want to allow users to install Microsoft R Open from the defaults channel while also having access to non-R packages from conda-forge, we need to add `r-mutex 1.* anacondar_1` as a run dependency. I don't use Microsoft R Open, and don't fully understand the consequences of adding this dependency, so we'll need someone willing to take charge on this.

conda-forge has [dropped support for win-32 builds](https://groups.google.com/forum/#!topic/conda-forge/jh8THDQCcjY), and the r-base recipes has multiple patches for win-32, so at some point we should remove these if they are no longer relevant.

To get a sense of the changes that have taken place on the defaults r-base (it's currently at 3.5.0), check out PR #45.

**Comment by dhirschfeld** [comment]
I think 4. is the most crucial for compatibility with the `defaults` channels, assuming that means implementing the `_r-mutex` scheme they've adopted there. I also think 1. is very important for compatibility as well.

As a `win-64` user I'm also fine with 5. and thought that policy had [already been adopted](https://github.com/conda-forge/staged-recipes/issues/5640).

**Comment by jdblischak** [comment]
> I think 4. is the most crucial for compatibility with the defaults channels, assuming that means implementing the _r-mutex scheme they've adopted there.

@dhirschfeld Would you like to take charge on this effort? As you can see in #34, I have regularly checked in on that issue without much success. I don't have the first idea how to manipulate tarballs on Anaconda Cloud.

> As a win-64 user I'm also fine with 5. and thought that policy had already been adopted.

The policy has been adopted, but that doesn't mean it's been executed. The r-base recipe has lots of patches that appear to be win-32 specific, so at some point someone needs to investigate to see which patches we can safely remove.

**Comment by jdblischak** [comment]
R 3.5.1 has been released ([release notes](https://stat.ethz.ch/pipermail/r-announce/2018/000630.html))

**Comment by jdblischak** [comment]
Another to-do when we get the chance: install `{native}icu` on Windows https://github.com/conda-forge/staged-recipes/issues/6690

**Comment by jakirkham** [comment]
FYI the compiler rebuild and R update have reached `r-base`. This is a good time to determine which of these need to be addressed with that PR ( https://github.com/conda-forge/r-base-feedstock/pull/60 ).

**Comment by jakirkham** [comment]
Now that PR ( https://github.com/conda-forge/r-base-feedstock/pull/61 ) is in, would be good to update this list accordingly.

**Comment by jdblischak** [comment]
PR #61 implemented the following updates:

* Re-arrange Windows R layout to be the same as Unix ([source line](https://github.com/conda-forge/r-base-feedstock/pull/61/files#diff-6434952e0196d29defa0a9742faddba6R202))
* Support MRO compatibility ([source line](https://github.com/conda-forge/r-base-feedstock/pull/61/files#diff-e178b687b10a71a3348107ae3154e44cR137)) 
* Install `{{native}}icu` on Windows ([source line](https://github.com/conda-forge/r-base-feedstock/pull/61/files#diff-e178b687b10a71a3348107ae3154e44cR117)) 

Both PR #60 and #61 edited the CI configuration files, so either or both of them succeeded in dropping support for win-32 because R 3.5.1 is no longer being [uploaded to Anaconda Cloud](https://anaconda.org/conda-forge/r-base/files?version=3.5.1). Strangely, although some of the win32 specific patches were deleted in PR #61, there are still 3 remaining:

* [0003-Win32-Do-not-link-static-libgcc.patch](https://github.com/conda-forge/r-base-feedstock/blob/95d45140cf768bf81c528698eb68619419670398/recipe/0003-Win32-Do-not-link-static-libgcc.patch)
* [0004-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch](https://github.com/conda-forge/r-base-feedstock/blob/95d45140cf768bf81c528698eb68619419670398/recipe/0004-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch)
* [0005-Win32-Prevent-conversion-of-R_ARCH-to-abs-Windows-pa.patch](https://github.com/conda-forge/r-base-feedstock/blob/95d45140cf768bf81c528698eb68619419670398/recipe/0005-Win32-Prevent-conversion-of-R_ARCH-to-abs-Windows-pa.patch)

**Comment by jdblischak** [comment]
I've updated the [checklist above](https://github.com/conda-forge/r-base-feedstock/issues/46#issue-334066933), and also followed up on Issues #34 and https://github.com/conda-forge/staged-recipes/issues/6690. Since it appears that all the issues have been addressed, I'm closing the issue.
